import test from 'node:test';
import assert from 'node:assert/strict';
import {RUNES} from '../lib/game/runes.ts';
import {normalize,recognize,resample} from '../lib/game/recognition.ts';
import {StrokeGate,isPointing} from '../lib/game/gating.ts';
import {blankAccuracy,type Point,type Stroke,type Landmark,type TrackingSample} from '../lib/game/types.ts';
import {createCombat,castSpell,tickCombat,warningMs} from '../lib/game/combat.ts';
import {createStudy,addTrial,currentTarget,rateDuel,finishDuel,studyCsv,summarize} from '../lib/game/study.ts';
const stroke=(points:Point[]):Stroke=>({points,startedAt:0,releasedAt:1000,endedAt:1150});
for(const rune of RUNES){
 test(rune.id+' recognizes translated, scaled, reversed, unevenly sampled paths',()=>{const dense=resample(rune.points,125);const variant=dense.map((p,i)=>({...p,x:p.x*.6+.2,y:p.y*.6+.15,t:i*i}));assert.equal(recognize(stroke(variant)).rune,rune.id);assert.equal(recognize(stroke([...variant].reverse())).rune,rune.id);});
 test(rune.id+' tolerates small rotation and noise',()=>{const a=.14,p=resample(rune.points,93).map((p,i)=>({...p,x:(p.x-.5)*Math.cos(a)-(p.y-.5)*Math.sin(a)+.5+Math.sin(i*3)*.004,y:(p.x-.5)*Math.sin(a)+(p.y-.5)*Math.cos(a)+.5+Math.cos(i*5)*.004}));assert.equal(recognize(stroke(p)).rune,rune.id);});
}
for(const rune of RUNES.filter(r=>r.closed))test(rune.id+' accepts shifted loop starting points',()=>{const p=resample(rune.points,64).slice(0,-1);for(const shift of [5,16,38]){const q=[...p.slice(shift),...p.slice(0,shift)];q.push(q[0]);assert.equal(recognize(stroke(q)).rune,rune.id);}});
test('zero-length paths remain finite and are rejected',()=>{const p=Array.from({length:6},()=>({x:.4,y:.4,t:0}));assert.ok(normalize(p).every(p=>Number.isFinite(p.x)));assert.equal(recognize(stroke(p)).reason,'too-small');});
test('horizontal lines normalize without division by zero; vertical line is rejected',()=>{const p=resample(RUNES[5].points);assert.ok(normalize(p).every(p=>p.y===0));assert.equal(recognize(stroke(p.map(p=>({...p,x:p.y,y:p.x})))).rune,null);});
test('unknown scribble, tiny and cancelled strokes do not cast',()=>{assert.equal(recognize(stroke(Array.from({length:50},(_,i)=>({x:Math.sin(i*1.7)*.4+.5,y:Math.cos(i*2.3)*.4+.5,t:i*20})))).rune,null);assert.equal(recognize({...stroke(RUNES[0].points),cancelled:'tracking-lost'}).reason,'tracking-lost');assert.equal(recognize({...stroke(RUNES[0].points),endedAt:21000}).reason,'too-long');});
function hand(pointing:boolean):Landmark[]{const l=Array.from({length:21},()=>({x:.5,y:.7,z:0}));l[0]={x:.5,y:.9,z:0};l[9]={x:.5,y:.65,z:0};l[5]={x:.4,y:.65,z:0};l[6]={x:.4,y:.5,z:0};l[8]={x:.4,y:pointing?.25:.68,z:0};for(const [a,b,c] of [[9,10,12],[13,14,16],[17,18,20]]){l[a]={x:.5,y:.65,z:0};l[b]={x:.5,y:.5,z:0};l[c]={x:.5,y:.7,z:0};}return l;}
function sample(t:number,pointing:boolean,present=true):TrackingSample{return {t,landmarks:present?hand(pointing):[],inferenceMs:8,frameStartedAt:t,receivedAt:t+8,handedness:'Right',aspect:1};}
test('pointing works for reflected left and right hands; curled index does not draw',()=>{assert.equal(isPointing(hand(true)),true);assert.equal(isPointing(hand(false)),false);assert.equal(isPointing(hand(true).map(p=>({...p,x:1-p.x}))),true);});
test('stable release required to arm; starts after 120ms and ends after a deliberate 350ms curl once',()=>{const g=new StrokeGate();g.feed(sample(10,false));g.feed(sample(170,false));assert.equal(g.state,'idle');g.feed(sample(200,true));g.feed(sample(300,true));assert.equal(g.state,'arming');g.feed(sample(330,true));assert.equal(g.state,'drawing');g.feed(sample(360,true));g.feed(sample(400,false));assert.equal(g.feed(sample(540,false)),null);g.feed(sample(600,false));const s=g.feed(sample(760,false));assert.ok(s);assert.equal(s.releasedAt,400);assert.equal(g.feed(sample(790,false)),null);});
test('tracking loss cancels and requires rearm; timestamp gaps cannot join strokes',()=>{const g=new StrokeGate();for(const [t,p] of [[10,false],[170,false],[200,true],[330,true]] as const)g.feed(sample(t,p));assert.equal(g.feed(sample(360,true,false)),null);assert.equal(g.feed(sample(900,true,false))?.cancelled,'tracking-lost');g.feed(sample(930,true));assert.equal(g.state,'rearm');g.feed(sample(950,false));g.feed(sample(1120,false));g.feed(sample(1150,true));g.feed(sample(1280,true));assert.equal(g.feed(sample(1900,true))?.cancelled,'tracking-lost');});
test('release jitter resumes the same stroke',()=>{const g=new StrokeGate();for(const [t,p] of [[10,false],[170,false],[200,true],[330,true],[360,false],[420,true]] as const)g.feed(sample(t,p));assert.equal(g.state,'drawing');assert.equal(g.startedAt,330);});
test('cooldowns prevent repeated damage and tick deterministically',()=>{const a=blankAccuracy();const c=createCombat('fixed',a);const first=castSpell(c,{rune:'fireball',at:0});assert.equal(first.state.opponent,92);assert.equal(c.opponent,100);assert.equal(castSpell(first.state,{rune:'fireball',at:10}).accepted,false);const later=tickCombat(first.state,4500,a);assert.equal(castSpell(later,{rune:'fireball',at:4500}).accepted,true);});
test('ward absorbs only next attack, dispel cancels, frost delays and mend caps',()=>{const a=blankAccuracy(),c=createCombat('fixed',a);const ward=castSpell(c,{rune:'ward',at:0}).state;const after=tickCombat(ward,4000,a);assert.equal(after.player,100);assert.equal(after.shield,false);assert.equal(tickCombat(after,7800,a).player,75);const frost=castSpell(c,{rune:'frost',at:0}).state;assert.equal(frost.remaining,7000);assert.equal(castSpell(c,{rune:'dispel',at:0}).state.phase,'recovery');assert.equal(castSpell({...c,player:90},{rune:'mend',at:0}).state.player,100);assert.equal(castSpell(c,{rune:'mend',at:0}).accepted,false);});
test('star stuns the Archivist and pauses its actions for three seconds',()=>{const a=blankAccuracy(),c=createCombat('fixed',a);const stunned=castSpell(c,{rune:'star',at:0}).state;assert.equal(stunned.opponentStun,3000);const twoSeconds=tickCombat(stunned,2000,a);assert.equal(twoSeconds.opponentStun,1000);assert.equal(twoSeconds.remaining,4000);const recovered=tickCombat(twoSeconds,1001,a);assert.equal(recovered.opponentStun,0);assert.equal(recovered.remaining,3999);});
test('defending halves damage and finished duels are immutable',()=>{const c={...createCombat('fixed',blankAccuracy()),phase:'defending' as const};assert.equal(castSpell(c,{rune:'fireball',at:0}).state.opponent,96);const finished={...c,outcome:'victory' as const};assert.equal(tickCombat(finished,2000,blankAccuracy()),finished);});
test('adaptive windows use per-rune prompted accuracy only',()=>{const a=blankAccuracy();a.ward={attempts:4,correct:1};assert.equal(warningMs('adaptive',a,'ward'),5875);assert.equal(warningMs('adaptive',a,'dispel'),4000);assert.equal(warningMs('fixed',a,'ward'),4000);});
test('study order is reproducible, balanced and counterbalanced',()=>{const a=createStudy(1,'test','test'),b=createStudy(1,'test','test'),c=createStudy(2,'test','test');assert.deepEqual(a.order,b.order);assert.notDeepEqual(a.order,c.order);for(const rune of RUNES)assert.equal(a.order.filter(r=>r===rune.id).length,10);assert.deepEqual(a.conditions,[...c.conditions].reverse());});
test('study advances through practice, measured trials, duels and ratings; rejects count',()=>{let s=createStudy(1,'test','test');for(let i=0;i<RUNES.length*12;i++){const target=currentTarget(s)!;const result=recognize(stroke(resample(RUNES.find(r=>r.id===target)!.points)));s=addTrial(s,i===RUNES.length*2?{...result,rune:null,reason:'ambiguous'}:result,stroke([]),{inferenceMs:8,frameToTrailMs:30,trackingHz:30,now:1200});}assert.equal(s.status,'duel-ready');assert.equal(Object.values(s.accuracy).reduce((n,a)=>n+a.attempts,0),RUNES.length*2);const summary=summarize(s.trials.filter(t=>t.phase==='measured'));assert.equal(summary.total,RUNES.length*10);assert.equal(summary.correct,RUNES.length*10-1);assert.equal(summary.rejected,1);for(const condition of s.conditions){s=finishDuel({...s,status:'duel'},{...createCombat(condition,s.accuracy),outcome:'victory'});s=rateDuel(s,{enjoyment:4,responsiveness:3,fatigue:2});}assert.equal(s.status,'complete');assert.ok(studyCsv(s).includes('"duel"'));assert.ok(studyCsv(s).includes('"trial"'));});
