import {INPUT_VERSION} from './gating.ts';
import {RUNE_IDS,blankAccuracy,type Accuracy,type RuneId,type RecognitionResult,type Stroke} from './types.ts';
import {COMBAT_VERSION,type Condition,type CombatState,type DuelStats} from './combat.ts';
import {RECOGNIZER_VERSION,THRESHOLDS} from './recognition.ts';
export type Trial={index:number;phase:'practice'|'measured';target:RuneId;predicted:RuneId|null;correct:boolean;reason:string|null;score:number;distance:number;runnerUpDistance:number;durationMs:number;releaseToCastMs:number;recognitionMs:number;inferenceMs:number;frameToTrailMs:number;trackingHz:number;at:string};
export type DuelRecord={stats?:DuelStats;condition:Condition;outcome:string;elapsedMs:number;playerHealth:number;opponentHealth:number;casts:number;blocked:number;ratings:{enjoyment:number;responsiveness:number;fatigue:number}|null};
export type Study={version:1;inputVersion?:string;combatVersion?:string;id:string;seed:number;createdAt:string;recognizerVersion:string;thresholds:typeof THRESHOLDS;status:'practice'|'measured'|'duel-ready'|'duel'|'rating'|'complete';practiceOrder:RuneId[];order:RuneId[];conditions:Condition[];trials:Trial[];duels:DuelRecord[];accuracy:Accuracy;machine:string;browser:string;interruptions:number};
export function seeded(seed:number){let a=seed>>>0;return ()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return ((t^(t>>>14))>>>0)/4294967296;};}
export function shuffle<T>(values:T[],seed:number):T[]{const a=[...values],random=seeded(seed);for(let i=a.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
export function createStudy(seed:number,machine:string,browser:string):Study{return {version:1,inputVersion:INPUT_VERSION,combatVersion:COMBAT_VERSION,id:'P-'+crypto.randomUUID().slice(0,8),seed,createdAt:new Date().toISOString(),recognizerVersion:RECOGNIZER_VERSION,thresholds:{...THRESHOLDS},status:'practice',practiceOrder:shuffle(RUNE_IDS.flatMap(r=>[r,r]),seed+1),order:shuffle(RUNE_IDS.flatMap(r=>Array.from({length:10},()=>r)),seed),conditions:seed%2?['adaptive','fixed']:['fixed','adaptive'],trials:[],duels:[],accuracy:blankAccuracy(),machine,browser,interruptions:0};}
export function currentTarget(s:Study):RuneId|null{if(s.status!=='practice'&&s.status!=='measured')return null;const n=s.trials.filter(t=>t.phase===s.status).length;return (s.status==='practice'?s.practiceOrder:s.order)[n]??null;}
export function addTrial(s:Study,result:RecognitionResult,stroke:Stroke,timing:{inferenceMs:number;frameToTrailMs:number;trackingHz:number;now:number}):Study{
 const target=currentTarget(s);if(!target)return s;const phase=s.status as 'practice'|'measured',correct=result.rune===target;
 const trial:Trial={index:s.trials.length+1,phase,target,predicted:result.rune,correct,reason:result.reason,score:result.score,distance:result.distance,runnerUpDistance:result.runnerUpDistance,durationMs:stroke.releasedAt-stroke.startedAt,releaseToCastMs:timing.now-stroke.releasedAt,recognitionMs:result.recognitionMs,inferenceMs:timing.inferenceMs,frameToTrailMs:timing.frameToTrailMs,trackingHz:timing.trackingHz,at:new Date().toISOString()};
 const next={...s,trials:[...s.trials,trial],accuracy:{...s.accuracy}};if(phase==='practice')next.accuracy[target]={attempts:s.accuracy[target].attempts+1,correct:s.accuracy[target].correct+Number(correct)};
 if(next.trials.filter(t=>t.phase===phase).length===(phase==='practice'?s.practiceOrder.length:s.order.length))next.status=phase==='practice'?'measured':'duel-ready';return next;
}
export function finishDuel(s:Study,c:CombatState):Study{return {...s,status:'rating',duels:[...s.duels,{condition:c.condition,outcome:c.outcome||'aborted',elapsedMs:c.elapsed,playerHealth:c.player,opponentHealth:c.opponent,casts:c.casts,blocked:c.blocked,stats:{...c.stats},ratings:null}]};}
export function rateDuel(s:Study,ratings:NonNullable<DuelRecord['ratings']>):Study{if(s.status!=='rating'||Object.values(ratings).some(v=>!Number.isInteger(v)||v<1||v>5))throw new Error('Rate each item from 1 to 5.');return {...s,status:s.duels.length===2?'complete':'duel-ready',duels:s.duels.map((d,i)=>i===s.duels.length-1?{...d,ratings}:d)};}
export function summarize(trials:Trial[]){const accuracy=blankAccuracy(),matrix=Object.fromEntries(RUNE_IDS.map(r=>[r,Object.fromEntries([...RUNE_IDS,'rejected'].map(c=>[c,0]))])) as Record<RuneId,Record<string,number>>;for(const t of trials){accuracy[t.target].attempts++;accuracy[t.target].correct+=Number(t.correct);matrix[t.target][t.predicted||'rejected']++;}return {accuracy,matrix,total:trials.length,correct:trials.filter(t=>t.correct).length,rejected:trials.filter(t=>!t.predicted).length};}
export function csv(rows:Record<string,unknown>[]):string{if(!rows.length)return '';const keys=[...new Set(rows.flatMap(Object.keys))];const cell=(v:unknown)=>'"'+String(v??'').replace(/"/g,'""')+'"';return [keys.map(cell).join(','),...rows.map(r=>keys.map(k=>cell(r[k])).join(','))].join('\r\n');}
export function studyCsv(s:Study):string{return csv([...s.trials.map(t=>({record:'trial',participant:s.id,seed:s.seed,machine:s.machine,browser:s.browser,interruptions:s.interruptions,recognizerVersion:s.recognizerVersion,inputVersion:s.inputVersion,combatVersion:s.combatVersion,...t})),...s.duels.map(d=>({record:'duel',combatVersion:s.combatVersion,participant:s.id,seed:s.seed,condition:d.condition,outcome:d.outcome,elapsedMs:d.elapsedMs,playerHealth:d.playerHealth,opponentHealth:d.opponentHealth,casts:d.casts,blocked:d.blocked,...d.stats,...d.ratings}))]);}

export function isCurrentStudy(s:Study):boolean{return s.inputVersion===INPUT_VERSION&&s.recognizerVersion===RECOGNIZER_VERSION&&s.combatVersion===COMBAT_VERSION;}
