export type RuneId='ward'|'fireball'|'lightning'|'frost'|'mend'|'dispel';
export type Point={x:number;y:number;t:number};
export type Landmark={x:number;y:number;z:number};
export type TrackingSample={t:number;landmarks:Landmark[];inferenceMs:number;frameStartedAt:number;receivedAt:number;handedness:string;aspect?:number};
export type Stroke={points:Point[];startedAt:number;releasedAt:number;endedAt:number;cancelled?:'tracking-lost'|'too-long'|'interrupted'};
export type RecognitionResult={rune:RuneId|null;candidate:RuneId|null;score:number;distance:number;runnerUpDistance:number;reason:string|null;recognitionMs:number};
export type SpellCommand={rune:RuneId;at:number};
export type Accuracy=Record<RuneId,{attempts:number;correct:number}>;
export const RUNE_IDS:RuneId[]=['ward','fireball','lightning','frost','mend','dispel'];
export function blankAccuracy():Accuracy{return Object.fromEntries(RUNE_IDS.map(id=>[id,{attempts:0,correct:0}])) as Accuracy;}
